"""Write the Mona Sans wordmark into the site: Logo.tsx, favicons, OG image, WhatsApp cover.

  python3 build_assets.py /path/to/Likwiid-website
"""
import os
import subprocess
import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

from monasans import CHOSEN, droplet, font, mark, num, wordmark

SITE = sys.argv[1] if len(sys.argv) > 1 else "/Users/gabriel/Documents/Likwiid/Likwiid-website"
PUB = os.path.join(SITE, "public")
OUT = os.path.dirname(os.path.abspath(__file__))

DARK_BG, DARK_FG, DARK_ACC, DARK_SUB = "#0F1115", "#E8EAF0", "#06B6D4", "#A3ABB8"
LIGHT_FG, LIGHT_ACC = "#1A1A2E", "#0E7490"

wm = wordmark(CHOSEN)
mk = mark(CHOSEN)
W, H = wm["w"], wm["h"]


def run(*args):
    subprocess.run(list(args), check=True)


def text_path(text, size, wght=450, tracking=0.0):
    """Lay out text with Mona Sans advances; returns (svg path at origin baseline, width)."""
    f = font(wght)
    gs = f.getGlyphSet()
    cmap = f.getBestCmap()
    hmtx = f["hmtx"]
    k = size / 1000
    pen = SVGPathPen(gs, ntos=num)
    x = 0.0
    for ch in text:
        g = cmap[ord(ch)]
        gs[g].draw(TransformPen(pen, (k, 0, 0, -k, x, 0)))
        x += hmtx[g][0] * k + tracking
    return pen.getCommands(), x - tracking


# ---------------------------------------------------------------- Logo.tsx
LOGO_TSX = f"""import {{ cn }} from '../../utils/cn'

interface LogoProps {{
  className?: string
  /** Fill for the droplet dots. Defaults to the site accent token. */
  accent?: string
}}

const DEFAULT_ACCENT = 'var(--color-accent-gold)'

// Wordmark drawn from Mona Sans SemiBold outlines (OFL-1.1) so the logo shares the heading
// voice. Letters fill with currentColor; both i dots are the brand droplet.
// Generated by the brand scripts (monasans.py, build_assets.py); edit there, not here.
const WORDMARK_LETTERS =
  '{wm["letters"]}'

const WORDMARK_DROPS =
  '{wm["drops"]}'

const MARK_STEMS = '{mk["stems"]}'

const MARK_DROPS =
  '{mk["drops"]}'

export function Logo({{ className, accent = DEFAULT_ACCENT }}: LogoProps) {{
  return (
    <svg
      viewBox="0 0 {num(W)} {num(H)}"
      role="img"
      aria-label="Likwiid"
      className={{cn('block w-auto shrink-0', className ?? 'h-6')}}
    >
      <path d={{WORDMARK_LETTERS}} fill="currentColor" />
      <path d={{WORDMARK_DROPS}} style={{{{ fill: accent }}}} />
    </svg>
  )
}}

export function LogoMark({{ className, accent = DEFAULT_ACCENT }}: LogoProps) {{
  return (
    <svg
      viewBox="0 0 64 64"
      role="img"
      aria-label="Likwiid"
      className={{cn('block w-auto shrink-0', className ?? 'h-6')}}
    >
      <path d={{MARK_STEMS}} fill="currentColor" />
      <path d={{MARK_DROPS}} style={{{{ fill: accent }}}} />
    </svg>
  )
}}
"""
open(os.path.join(SITE, "src/components/ui/Logo.tsx"), "w").write(LOGO_TSX)

# ---------------------------------------------------------------- favicon.svg
FAVICON = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <style>
    .s {{ fill: {LIGHT_FG}; }}
    .d {{ fill: {LIGHT_ACC}; }}
    @media (prefers-color-scheme: dark) {{
      .s {{ fill: {DARK_FG}; }}
      .d {{ fill: {DARK_ACC}; }}
    }}
  </style>
  <path class="s" d="{mk["stems"]}"/>
  <path class="d" d="{mk["drops"]}"/>
</svg>
"""
open(os.path.join(PUB, "favicon.svg"), "w").write(FAVICON)


# ---------------------------------------------------------------- icon tiles (ico + apple touch)
def tile(size_vb, rx, scale):
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size_vb} {size_vb}">'
        f'<rect width="{size_vb}" height="{size_vb}" rx="{rx}" fill="{DARK_BG}"/>'
        f'<g transform="translate({size_vb / 2} {size_vb / 2}) scale({scale}) translate(-32 -32)">'
        f'<path d="{mk["stems"]}" fill="{DARK_FG}"/><path d="{mk["drops"]}" fill="{DARK_ACC}"/></g></svg>'
    )


# 16px: hand placed on the pixel grid (stems 3px wide, 2px apart; droplet as wide as the stem)
d16 = "".join(droplet(cx, 4.0, 1.5)[0] for cx in (5.5, 10.5))
ICON16 = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">'
    f'<rect width="16" height="16" rx="3.5" fill="{DARK_BG}"/>'
    f'<path d="M4 14V7H7V14ZM9 14V7H12V14Z" fill="{DARK_FG}"/><path d="{d16}" fill="{DARK_ACC}"/></svg>'
)
open(os.path.join(OUT, "ms-icon16.svg"), "w").write(ICON16)
open(os.path.join(OUT, "ms-icon-tile.svg"), "w").write(tile(64, 14, 0.86))
run("rsvg-convert", "-w", "16", os.path.join(OUT, "ms-icon16.svg"), "-o", os.path.join(OUT, "ms-ico16.png"))
for s in (32, 48):
    run("rsvg-convert", "-w", str(s), os.path.join(OUT, "ms-icon-tile.svg"), "-o", os.path.join(OUT, f"ms-ico{s}.png"))
run(
    "magick",
    os.path.join(OUT, "ms-ico16.png"),
    os.path.join(OUT, "ms-ico32.png"),
    os.path.join(OUT, "ms-ico48.png"),
    os.path.join(PUB, "favicon.ico"),
)

open(os.path.join(OUT, "ms-apple-touch.svg"), "w").write(tile(180, 40, 2.1))
run("rsvg-convert", "-w", "180", os.path.join(OUT, "ms-apple-touch.svg"), "-o", os.path.join(PUB, "apple-touch-icon.png"))


# ---------------------------------------------------------------- OG image + WhatsApp cover
def card(cw, ch, wm_w, wm_top, sub_size, sub_base):
    sc = wm_w / W
    x = (cw - wm_w) / 2
    sub, sub_w = text_path("Software studio, Beirut", sub_size, wght=450, tracking=0.4)
    sx = (cw - sub_w) / 2
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{cw}" height="{ch}" viewBox="0 0 {cw} {ch}">\n'
        f'  <rect width="{cw}" height="{ch}" fill="{DARK_BG}"/>\n'
        f'  <g transform="translate({num(x)} {num(wm_top)}) scale({sc:.4f})">\n'
        f'    <path d="{wm["letters"]}" fill="{DARK_FG}"/>\n'
        f'    <path d="{wm["drops"]}" fill="{DARK_ACC}"/>\n'
        f"  </g>\n"
        f'  <g transform="translate({num(sx)} {num(sub_base)})" aria-label="Software studio, Beirut">\n'
        f'    <path d="{sub}" fill="{DARK_SUB}"/>\n'
        f"  </g>\n"
        f"</svg>\n"
    )


og = card(1200, 630, 600, 186, 34, 452)
open(os.path.join(PUB, "og-image.svg"), "w").write(og)
run("rsvg-convert", "-w", "1200", os.path.join(PUB, "og-image.svg"), "-o", os.path.join(PUB, "og-image.png"))

wa = card(1000, 1000, 600, 372, 34, 636)
open(os.path.join(OUT, "ms-whatsapp-cover.svg"), "w").write(wa)
run(
    "rsvg-convert",
    "-w",
    "1000",
    os.path.join(OUT, "ms-whatsapp-cover.svg"),
    "-o",
    os.path.join(PUB, "likwiid-whatsapp-cover.png"),
)

for p in ("og-image.png", "likwiid-whatsapp-cover.png", "apple-touch-icon.png"):
    run("magick", os.path.join(PUB, p), "-strip", "-define", "png:compression-level=9", os.path.join(PUB, p))
print("wordmark viewBox 0 0", num(W), num(H))
