import { cn } from '../../utils/cn'

interface LogoProps {
  className?: string
  /** Fill for the droplet dots. Defaults to the site accent token. */
  accent?: string
}

const DEFAULT_ACCENT = 'var(--color-accent-gold)'

// Wordmark drawn from Mona Sans SemiBold outlines (OFL-1.1) so the logo shares the heading
// voice. Letters fill with currentColor; both i dots are the brand droplet.
// Generated by the brand scripts (monasans.py, build_assets.py); edit there, not here.
const WORDMARK_LETTERS =
  'M0 159.8V14H27.2V159.8ZM50.4 159.8V52.9H77.6V159.8ZM100.8 159.8V14H128.4V98.9L137.3 88.8L171 52.9H204.6L163.3 95L205.6 159.8H173.6L150.7 124.2L144.3 113.2L128.4 128.8V159.8ZM235 159.8 209.6 52.9H237.4L249.6 108.2L254.8 135.5H256L260.5 108.2L271.3 52.9H301.7L312.7 108.2L317.3 135.9H318.5L323.5 108.2L335.7 52.9H362.5L336.7 159.8H300.9L290.7 112.3L286 84.4H285L280.4 112.3L270.7 159.8ZM374.8 159.8V52.9H402V159.8ZM425.2 159.8V52.9H452.4V159.8ZM513.8 161.6Q504.1 161.6 496 157.9Q487.9 154.1 482.1 147Q476.3 139.9 473.2 129.6Q470.1 119.4 470.1 106.3Q470.1 88.8 475.6 76.4Q481.1 64 490.9 57.5Q500.7 51 513.8 51Q522 51 528.8 53.5Q535.7 56.1 540.5 60.7Q545.4 65.3 547.6 71.6H548.8V14H576V159.8H550.1L549.1 141H547.6Q544.2 150.3 535.2 156Q526.1 161.6 513.8 161.6ZM523.5 139.5Q531.9 139.5 537.5 135.8Q543.1 132.1 545.9 125.8Q548.8 119.5 548.8 111.8V100.8Q548.8 92.8 545.8 86.5Q542.8 80.2 537.3 76.6Q531.8 73 524.1 73Q515.5 73 509.7 77Q503.8 81.1 500.9 88.5Q497.9 96 497.9 106.3Q497.9 116.4 500.8 124Q503.6 131.5 509.3 135.5Q515 139.5 523.5 139.5Z'

const WORDMARK_DROPS =
  'M64 0C66.5 8.4 77.6 18.1 77.6 26.5A13.6 13.6 0 0 1 50.4 26.5C50.4 18.1 61.6 8.4 64 0ZM388.4 0C390.9 8.4 402 18.1 402 26.5A13.6 13.6 0 0 1 374.8 26.5C374.8 18.1 386 8.4 388.4 0ZM438.8 0C441.3 8.4 452.4 18.1 452.4 26.5A13.6 13.6 0 0 1 425.2 26.5C425.2 18.1 436.4 8.4 438.8 0Z'

const MARK_STEMS = 'M14 60V28H26V60ZM38 60V28H50V60Z'

const MARK_DROPS =
  'M20 4.7C21.1 8.4 26 12.6 26 16.4A6 6 0 0 1 14 16.4C14 12.6 18.9 8.4 20 4.7ZM44 4.7C45.1 8.4 50 12.6 50 16.4A6 6 0 0 1 38 16.4C38 12.6 42.9 8.4 44 4.7Z'

export function Logo({ className, accent = DEFAULT_ACCENT }: LogoProps) {
  return (
    <svg
      viewBox="0 0 576 161.6"
      role="img"
      aria-label="Likwiid"
      className={cn('block w-auto shrink-0', className ?? 'h-6')}
    >
      <path d={WORDMARK_LETTERS} fill="currentColor" />
      <path d={WORDMARK_DROPS} style={{ fill: accent }} />
    </svg>
  )
}

export function LogoMark({ className, accent = DEFAULT_ACCENT }: LogoProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      role="img"
      aria-label="Likwiid"
      className={cn('block w-auto shrink-0', className ?? 'h-6')}
    >
      <path d={MARK_STEMS} fill="currentColor" />
      <path d={MARK_DROPS} style={{ fill: accent }} />
    </svg>
  )
}
